steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/snow-flask-whoami-gpc:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/snow-flask-whoami-gpc:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'snow-flask-whoami-gpc'
      - '--image=gcr.io/$PROJECT_ID/snow-flask-whoami-gpc:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=USERNAME=${_SNOWFLAKE_USERNAME},PASSWORD=${_SNOWFLAKE_PASSWORD},REGION=${_SNOWFLAKE_REGION}'

images:
  - 'gcr.io/$PROJECT_ID/snow-flask-whoami-gpc:$COMMIT_SHA'

substitutions:
  _SNOWFLAKE_USERNAME: ''  # Set these in Cloud Build trigger
  _SNOWFLAKE_PASSWORD: ''
  _SNOWFLAKE_REGION: ''
